name: Deploy Nuxt App

on:
  push:
    branches:
      - main  # 只有推送到 main 分支时才触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:   # <--- 这是父级
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # 关键点：script 必须缩进在 with 里面，不要和 with 对齐！
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH=$PATH:$(npm config get prefix)/bin
            cd ~/code/AIpenglow
            git fetch --all
            git reset --hard origin/main
            rm -rf .output .nuxt
            npm install
            NODE_OPTIONS="--max-old-space-size=1536" npm run build
            pm2 restart AIpenglow-nuxt-app || pm2 start .output/server/index.mjs --name "AIpenglow-nuxt-app"
            pm2 save